import Deps.*

ThisBuild / scalaVersion := "3.3.6"
ThisBuild / semanticdbEnabled := true

lazy val root = (project in file("."))
    .settings(
        name := "scala-cli-exercises",

        Compile / scalaSource := baseDirectory.value / "src",
        Test / scalaSource := baseDirectory.value / "test",

        libraryDependencies += toolkit,
        libraryDependencies += (toolkitTest % Test),

        // generated by scala-cli, based on xebia-se-toolkit.scala 
        libraryDependencies ++= scalaCliDeps,
        libraryDependencies ++= scalaCliTestDeps,
    )
